# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizapp', '0003_remove_drink_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='picture',
            field=models.CharField(default=b'string', max_length=1000),
        ),
    ]
