# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizapp', '0004_drink_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='picture',
            field=models.FileField(upload_to=b''),
        ),
    ]
